name: flutter_example
uses-material-deisgn: true
dependencies:
  collection: '>=1.9.1 <2.0.0'
  intl: '>=0.14.0 <0.15.0'
  meta: ^1.0.3
  vector_math:
    path: C:/Users/Michael/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/vector_math-2.0.3/

  # async and http_parser can be removed when we move to using dart-lang/http
  # directly.
  async: "^1.10.0"
  http_parser: ">=0.0.1 <4.0.0"